apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-worker
  namespace: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-worker
  template:
    metadata:
      labels:
        app: inventory-worker
    spec:
      containers:
        - name: inventory-worker
          image: orders/inventory-worker:dev
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_URL
              value: amqp://orders:orders-dev-password@rabbitmq:5672/%2F
